import 'package:tarot/src/features/cards/domain/card.dart';

final List<Card> kDeyaCardsFire = [
  Card(
    id: "76",
    title: "Card 76",
    description: "Description for Card 76",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-76.png",
    order: 1,
  ),
  Card(
    id: "13",
    title: "Card 13",
    description: "Description for Card 13",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-13.png",
    order: 2,
  ),
  Card(
    id: "2",
    title: "Card 2",
    description: "Description for Card 2",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-2.png",
    order: 3,
  ),
  Card(
    id: "92",
    title: "Card 92",
    description: "Description for Card 92",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-92.png",
    order: 4,
  ),
  Card(
    id: "57",
    title: "Card 57",
    description: "Description for Card 57",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-57.png",
    order: 5,
  ),
  Card(
    id: "98",
    title: "Card 98",
    description: "Description for Card 98",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-98.png",
    order: 6,
  ),
  Card(
    id: "107",
    title: "Card 107",
    description: "Description for Card 107",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-107.png",
    order: 7,
  ),
  Card(
    id: "101",
    title: "Card 101",
    description: "Description for Card 101",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-101.png",
    order: 8,
  ),
  Card(
    id: "37",
    title: "Card 37",
    description: "Description for Card 37",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-37.png",
    order: 9,
  ),
  Card(
    id: "71",
    title: "Card 71",
    description: "Description for Card 71",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-71.png",
    order: 10,
  ),
  Card(
    id: "105",
    title: "Card 105",
    description: "Description for Card 105",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-105.png",
    order: 11,
  ),
  Card(
    id: "77",
    title: "Card 77",
    description: "Description for Card 77",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-77.png",
    order: 12,
  ),
  Card(
    id: "60",
    title: "Card 60",
    description: "Description for Card 60",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-60.png",
    order: 13,
  ),
  Card(
    id: "72",
    title: "Card 72",
    description: "Description for Card 72",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-72.png",
    order: 14,
  ),
  Card(
    id: "94",
    title: "Card 94",
    description: "Description for Card 94",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-94.png",
    order: 15,
  ),
  Card(
    id: "85",
    title: "Card 85",
    description: "Description for Card 85",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-85.png",
    order: 16,
  ),
  Card(
    id: "99",
    title: "Card 99",
    description: "Description for Card 99",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-99.png",
    order: 17,
  ),
  Card(
    id: "39",
    title: "Card 39",
    description: "Description for Card 39",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-39.png",
    order: 18,
  ),
  Card(
    id: "62",
    title: "Card 62",
    description: "Description for Card 62",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-62.png",
    order: 19,
  ),
  Card(
    id: "66",
    title: "Card 66",
    description: "Description for Card 66",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-66.png",
    order: 20,
  ),
  Card(
    id: "75",
    title: "Card 75",
    description: "Description for Card 75",
    type: CardType.deya,
    topic: CardTopic.fire,
    imagePath: "assets/images/card-75.png",
    order: 21,
  ),
];
final List<Card> kDeyaCardsHome = [
  Card(
    id: "52",
    title: "Spiral",
    description: "A symbol of home and grounding.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/spiral-bold.png",
    order: 1,
  ),
  Card(
    id: "91",
    title: "Home",
    description: "A symbol of safety and comfort.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/home-bold.png",
    order: 2,
  ),
  Card(
    id: "79",
    title: "Family",
    description: "A symbol of love and support.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/family-bold.png",
    order: 3,
  ),
  Card(
    id: "14",
    title: "Roots",
    description: "A symbol of stability and grounding.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/roots-bold.png",
    order: 4,
  ),
  Card(
    id: "7",
    title: "Hearth",
    description: "A symbol of warmth and security.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/hearth-bold.png",
    order: 5,
  ),
  Card(
    id: "9",
    title: "Nest",
    description: "A symbol of comfort and protection.",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/nest-bold.png",
    order: 6,
  ),
  Card(
    id: "103",
    title: "Card 103",
    description: "Description for Card 103",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-103.png",
    order: 7,
  ),
  Card(
    id: "89",
    title: "Card 89",
    description: "Description for Card 89",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-89.png",
    order: 8,
  ),
  Card(
    id: "32",
    title: "Card 32",
    description: "Description for Card 32",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-32.png",
    order: 9,
  ),
  Card(
    id: "45",
    title: "Card 45",
    description: "Description for Card 45",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-45.png",
    order: 10,
  ),
  Card(
    id: "30",
    title: "Card 30",
    description: "Description for Card 30",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-30.png",
    order: 11,
  ),
  Card(
    id: "83",
    title: "Card 83",
    description: "Description for Card 83",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-83.png",
    order: 12,
  ),
  Card(
    id: "15",
    title: "Card 15",
    description: "Description for Card 15",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-15.png",
    order: 13,
  ),
  Card(
    id: "27",
    title: "Card 27",
    description: "Description for Card 27",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-27.png",
    order: 14,
  ),
  Card(
    id: "67",
    title: "Card 67",
    description: "Description for Card 67",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-67.png",
    order: 15,
  ),
  Card(
    id: "1",
    title: "Card 1",
    description: "Description for Card 1",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-1.png",
    order: 16,
  ),
  Card(
    id: "48",
    title: "Card 48",
    description: "Description for Card 48",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-48.png",
    order: 17,
  ),
  Card(
    id: "68",
    title: "Card 68",
    description: "Description for Card 68",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-68.png",
    order: 18,
  ),
  Card(
    id: "3",
    title: "Card 3",
    description: "Description for Card 3",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-3.png",
    order: 19,
  ),
  Card(
    id: "78",
    title: "Card 78",
    description: "Description for Card 78",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-78.png",
    order: 20,
  ),
  Card(
    id: "38",
    title: "Card 38",
    description: "Description for Card 38",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-38.png",
    order: 21,
  ),
  Card(
    id: "24",
    title: "Card 24",
    description: "Description for Card 24",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-24.png",
    order: 22,
  ),
  Card(
    id: "64",
    title: "Card 64",
    description: "Description for Card 64",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-64.png",
    order: 23,
  ),
  Card(
    id: "100",
    title: "Card 100",
    description: "Description for Card 100",
    type: CardType.deya,
    topic: CardTopic.home,
    imagePath: "assets/images/card-100.png",
    order: 24,
  ),
];
final kDeyaCardsEarth = [
  Card(
    id: "44",
    title: "Card 44",
    description: "Description for Card 44",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-44.png",
    order: 1,
  ),
  Card(
    id: "11",
    title: "Card 11",
    description: "Description for Card 11",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-11.png",
    order: 2,
  ),
  Card(
    id: "42",
    title: "Card 42",
    description: "Description for Card 42",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-42.png",
    order: 3,
  ),
  Card(
    id: "31",
    title: "Card 31",
    description: "Description for Card 31",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-31.png",
    order: 4,
  ),
  Card(
    id: "69",
    title: "Card 69",
    description: "Description for Card 69",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-69.png",
    order: 5,
  ),
  Card(
    id: "25",
    title: "Card 25",
    description: "Description for Card 25",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-25.png",
    order: 6,
  ),
  Card(
    id: "81",
    title: "Card 81",
    description: "Description for Card 81",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-81.png",
    order: 7,
  ),
  Card(
    id: "26",
    title: "Card 26",
    description: "Description for Card 26",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-26.png",
    order: 8,
  ),
  Card(
    id: "53",
    title: "Card 53",
    description: "Description for Card 53",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-53.png",
    order: 9,
  ),
  Card(
    id: "97",
    title: "Card 97",
    description: "Description for Card 97",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-97.png",
    order: 10,
  ),
  Card(
    id: "17",
    title: "Card 17",
    description: "Description for Card 17",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-17.png",
    order: 11,
  ),
  Card(
    id: "54",
    title: "Card 54",
    description: "Description for Card 54",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-54.png",
    order: 12,
  ),
  Card(
    id: "55",
    title: "Card 55",
    description: "Description for Card 55",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-55.png",
    order: 13,
  ),
  Card(
    id: "33",
    title: "Card 33",
    description: "Description for Card 33",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-33.png",
    order: 14,
  ),
  Card(
    id: "90",
    title: "Card 90",
    description: "Description for Card 90",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-90.png",
    order: 15,
  ),
  Card(
    id: "93",
    title: "Card 93",
    description: "Description for Card 93",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-93.png",
    order: 16,
  ),
  Card(
    id: "74",
    title: "Card 74",
    description: "Description for Card 74",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-74.png",
    order: 17,
  ),
  Card(
    id: "8",
    title: "Card 8",
    description: "Description for Card 8",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-8.png",
    order: 18,
  ),
  Card(
    id: "40",
    title: "Card 40",
    description: "Description for Card 40",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-40.png",
    order: 19,
  ),
  Card(
    id: "73",
    title: "Card 73",
    description: "Description for Card 73",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-73.png",
    order: 20,
  ),
  Card(
    id: "82",
    title: "Card 82",
    description: "Description for Card 82",
    type: CardType.deya,
    topic: CardTopic.earth,
    imagePath: "assets/images/card-82.png",
    order: 21,
  ),
];
final kDeyaCardsWind = [
  Card(
    id: "35",
    title: "Card 35",
    description: "Description for Card 35",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-35.png",
    order: 1,
  ),
  Card(
    id: "22",
    title: "Card 22",
    description: "Description for Card 22",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-22.png",
    order: 2,
  ),
  Card(
    id: "50",
    title: "Card 50",
    description: "Description for Card 50",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-50.png",
    order: 3,
  ),
  Card(
    id: "41",
    title: "Card 41",
    description: "Description for Card 41",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-41.png",
    order: 4,
  ),
  Card(
    id: "18",
    title: "Card 18",
    description: "Description for Card 18",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-18.png",
    order: 5,
  ),
  Card(
    id: "46",
    title: "Card 46",
    description: "Description for Card 46",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-46.png",
    order: 6,
  ),
  Card(
    id: "102",
    title: "Card 102",
    description: "Description for Card 102",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-102.png",
    order: 7,
  ),
  Card(
    id: "80",
    title: "Card 80",
    description: "Description for Card 80",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-80.png",
    order: 8,
  ),
  Card(
    id: "10",
    title: "Card 10",
    description: "Description for Card 10",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-10.png",
    order: 9,
  ),
  Card(
    id: "36",
    title: "Card 36",
    description: "Description for Card 36",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-36.png",
    order: 10,
  ),
  Card(
    id: "88",
    title: "Card 88",
    description: "Description for Card 88",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-88.png",
    order: 11,
  ),
  Card(
    id: "84",
    title: "Card 84",
    description: "Description for Card 84",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-84.png",
    order: 12,
  ),
  Card(
    id: "34",
    title: "Card 34",
    description: "Description for Card 34",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-34.png",
    order: 13,
  ),
  Card(
    id: "4",
    title: "Card 4",
    description: "Description for Card 4",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-4.png",
    order: 14,
  ),
  Card(
    id: "86",
    title: "Card 86",
    description: "Description for Card 86",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-86.png",
    order: 15,
  ),
  Card(
    id: "29",
    title: "Card 29",
    description: "Description for Card 29",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-29.png",
    order: 16,
  ),
  Card(
    id: "12",
    title: "Card 12",
    description: "Description for Card 12",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-12.png",
    order: 17,
  ),
  Card(
    id: "95",
    title: "Card 95",
    description: "Description for Card 95",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-95.png",
    order: 18,
  ),
  Card(
    id: "58",
    title: "Card 58",
    description: "Description for Card 58",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-58.png",
    order: 19,
  ),
  Card(
    id: "70",
    title: "Card 70",
    description: "Description for Card 70",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-70.png",
    order: 20,
  ),
  Card(
    id: "96",
    title: "Card 96",
    description: "Description for Card 96",
    type: CardType.deya,
    topic: CardTopic.wind,
    imagePath: "assets/images/card-96.png",
    order: 21,
  ),
];
final List<Card> kDeyaCardsWater = [
  Card(
    id: "5",
    title: "Card 5",
    description: "Description for Card 5",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-5.png",
    order: 1,
  ),
  Card(
    id: "87",
    title: "Card 87",
    description: "Description for Card 87",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-87.png",
    order: 2,
  ),
  Card(
    id: "16",
    title: "Card 16",
    description: "Description for Card 16",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-16.png",
    order: 3,
  ),
  Card(
    id: "20",
    title: "Card 20",
    description: "Description for Card 20",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-20.png",
    order: 4,
  ),
  Card(
    id: "106",
    title: "Card 106",
    description: "Description for Card 106",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-106.png",
    order: 5,
  ),
  Card(
    id: "108",
    title: "Card 108",
    description: "Description for Card 108",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-108.png",
    order: 6,
  ),
  Card(
    id: "59",
    title: "Card 59",
    description: "Description for Card 59",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-59.png",
    order: 7,
  ),
  Card(
    id: "104",
    title: "Card 104",
    description: "Description for Card 104",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-104.png",
    order: 8,
  ),
  Card(
    id: "6",
    title: "Card 6",
    description: "Description for Card 6",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-6.png",
    order: 9,
  ),
  Card(
    id: "23",
    title: "Card 23",
    description: "Description for Card 23",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-23.png",
    order: 10,
  ),
  Card(
    id: "19",
    title: "Card 19",
    description: "Description for Card 19",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-19.png",
    order: 11,
  ),
  Card(
    id: "21",
    title: "Card 21",
    description: "Description for Card 21",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-21.png",
    order: 12,
  ),
  Card(
    id: "56",
    title: "Card 56",
    description: "Description for Card 56",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-56.png",
    order: 13,
  ),
  Card(
    id: "63",
    title: "Card 63",
    description: "Description for Card 63",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-63.png",
    order: 14,
  ),
  Card(
    id: "65",
    title: "Card 65",
    description: "Description for Card 65",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-65.png",
    order: 15,
  ),
  Card(
    id: "49",
    title: "Card 49",
    description: "Description for Card 49",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-49.png",
    order: 16,
  ),
  Card(
    id: "51",
    title: "Card 51",
    description: "Description for Card 51",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-51.png",
    order: 17,
  ),
  Card(
    id: "61",
    title: "Card 61",
    description: "Description for Card 61",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-61.png",
    order: 18,
  ),
  Card(
    id: "43",
    title: "Card 43",
    description: "Description for Card 43",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-43.png",
    order: 19,
  ),
  Card(
    id: "28",
    title: "Card 28",
    description: "Description for Card 28",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-28.png",
    order: 20,
  ),
  Card(
    id: "47",
    title: "Card 47",
    description: "Description for Card 47",
    type: CardType.deya,
    topic: CardTopic.water,
    imagePath: "assets/images/card-47.png",
    order: 21,
  ),
];
final kRiderWaiteCardsHome = [
  Card(
    id: "0",
    title: "Колесница",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 1,
  ),
  Card(
    id: "1",
    title: "Дурак",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 2,
  ),
  Card(
    id: "2",
    title: "Маг",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 3,
  ),
  Card(
    id: "3",
    title: "Жрица",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 4,
  ),
  Card(
    id: "4",
    title: "Императрица",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 5,
  ),
  Card(
    id: "5",
    title: "Император",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 6,
  ),
  Card(
    id: "6",
    title: "Иерофант",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 7,
  ),
  Card(
    id: "7",
    title: "Влюбленные",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 8,
  ),
  Card(
    id: "8",
    title: "Колесо Фортуны",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 9,
  ),
  Card(
    id: "9",
    title: "Сила",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 10,
  ),
  Card(
    id: "10",
    title: "Отшельник",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 11,
  ),
  Card(
    id: "11",
    title: "Справедливость",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 12,
  ),
  Card(
    id: "12",
    title: "Повешенный",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 13,
  ),
  Card(
    id: "13",
    title: "Смерть",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 14,
  ),
  Card(
    id: "14",
    title: "Умеренность",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 15,
  ),
  Card(
    id: "15",
    title: "Дьявол",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 16,
  ),
  Card(
    id: "16",
    title: "Башня",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 17,
  ),
  Card(
    id: "17",
    title: "Звезда",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 18,
  ),
  Card(
    id: "18",
    title: "Луна",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 19,
  ),
  Card(
    id: "19",
    title: "Солнце",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 20,
  ),
  Card(
    id: "20",
    title: "Суд",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 21,
  ),
  Card(
    id: "21",
    title: "Мир",
    description: "",
    type: CardType.riderWaite,
    topic: CardTopic.home,
    imagePath: "",
    order: 22,
  ),
];
final kRiderWaiteCardsWater = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
];
final kRiderWaiteCardsFire = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
];
final kRiderWaiteCardsEarth = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
];
final kRiderWaiteCardsWind = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
];
